# Generated by Django 5.2.5 on 2025-08-31 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '__first__'),
        ('Contract', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_link_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente de Assinatura'), ('SIGNED', 'Assinado')], default='PENDING', max_length=10)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Imagem da Assinatura')),
                ('signed_pdf_file', models.FileField(blank=True, null=True, upload_to='signed_contracts/', verbose_name='PDF Assinado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.customer', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.service', verbose_name='Serviço')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contract.contracttemplate', verbose_name='Modelo Utilizado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
