# Generated by Django 5.2.5 on 2025-08-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Modelo')),
                ('content_html', models.TextField(help_text='Use variáveis como {{nome_cliente}}, {{email_cliente}}, {{cpf_cliente}}, {{data_assinatura}}.', verbose_name='Conteúdo (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Contrato',
                'verbose_name_plural': 'Modelos de Contratos',
            },
        ),
    ]
