# Generated by Django 5.2.5 on 2025-08-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes_painel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDireito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Área do Direito')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Categoria do Serviço')),
            ],
        ),
    ]
